package com.hwb.aianswerer.ui.theme

import androidx.compose.ui.graphics.Color

// 亮色主题 - 明亮清新的蓝色调
val md_theme_light_primary = Color(0xFF4A6CF7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00105A)
val md_theme_light_secondary = Color(0xFF5A5F72)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDFE3FA)
val md_theme_light_onSecondaryContainer = Color(0xFF171C2B)
val md_theme_light_tertiary = Color(0xFF745570)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F6)
val md_theme_light_onTertiaryContainer = Color(0xFF2C122A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6F5F3)
val md_theme_light_onBackground = Color(0xFF1A1B21)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1B21)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF2F3036)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F8)
val md_theme_light_inversePrimary = Color(0xFFBAC3FF)

// 暗色主题
val md_theme_dark_primary = Color(0xFF2563EB)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF3A4A8F)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E4FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253140)
val md_theme_dark_secondaryContainer = Color(0xFF3C4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E3F8)
val md_theme_dark_tertiary = Color(0xFF705575)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFF52405F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3DAFF)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF0F1118)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1D27)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF252836)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_outlineVariant = Color(0xFF3A3D4A)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1D27)
val md_theme_dark_inversePrimary = Color(0xFF4F5FD1)
